handle_neutral_feedback_task:
  description: >
    Recommend alternative restaurants to the customer following neutral feedback. Suggested options include: The Good Vibes Only (for Italian), Kodi Kura Chitti Gare (for Indian), and Raise the Bar (for Bar).
  expected_output: >
    A list of alternative restaurants offering better dining experiences, with options from: The Good Vibes Only (for Italian), Kodi Kura Chitti Gare (for Indian), and Raise the Bar (for Bar).
  agent: neutral_feedback_agent
